language: go

go:
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -v -coverpkg=./... -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)